### ISSUE TITLE
Use _fixed_process for physics

### ISSUE THREAD

**Issue by bojidar-bg** [NathanLovato/Godot-simple-platformer#1]
Current code in [player.gd](https://github.com/NathanLovato/Godot-simple-platformer/blob/master/player.gd#L35) uses `_process` to deal with physics, which means that it would behave differently on different framerates.

**Comment by NathanLovato** [comment]
Yes it does, and that's what shows the corresponding video tutorial. Don't bother too much with this repo, it's only available to go along with the Youtube videos, but I'll rather add a note for people to check the newer tutorials. It's not that great overall.

Many game engines I've used only provide a _process equivalent, so this part shouldn't be a big deal. Unless the framerate drops extremely low, it should not make a noticeable difference, right?

**Comment by NathanLovato** [comment]
Added a note that the tutorial is *outdated* so people get to watch the newer series instead. Thanks for the issue! https://github.com/NathanLovato/Godot-simple-platformer/commit/31db1f781f4fa2b7e29da5d30f8b20d717bc099f
